"""Role

Revision ID: 9b1c7a1fe475
Revises: 4d5add2a8b3f
Create Date: 2025-01-24 13:13:37.584172

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9b1c7a1fe475'
down_revision = '4d5add2a8b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный ключ'),
        sa.Column('role_code', sa.String(length=100), nullable=False, comment='Код роли'),
        sa.Column('role_name', sa.String(length=150), nullable=False, comment='Имя роли'),
        sa.Column('role_desc', sa.String(length=200), nullable=True, comment='Описание роли'),
        sa.Column('owner_cr', sa.Integer(), nullable=True, comment='Код создателя'),
        sa.Column('owner_up', sa.Integer(), nullable=True, comment='Код редактора'),
        sa.Column('dt_cr', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Создана'),
        sa.Column('dt_up', sa.DateTime(), nullable=True, comment='Изменена'),
        sa.Column('status', sa.Boolean(), server_default='true', nullable=False, comment='Статус'),
        sa.PrimaryKeyConstraint('id', name=op.f('roles_pk'))
    )
    op.create_index(op.f('roles_ix_status'), 'roles', ['status'], unique=False)
    op.create_index('roles_uq_role_code', 'roles', [sa.text('lower(role_code)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('roles_uq_role_code', table_name='roles')
    op.drop_index(op.f('roles_ix_status'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
