"""rel1

Revision ID: 7986a23639e5
Revises: 4d5add2a8b3f
Create Date: 2025-01-24 15:23:35.196842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7986a23639e5'
down_revision = '4d5add2a8b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_perms',
        sa.Column('user_id', sa.Integer(), nullable=False, comment='Код пользователя'),
        sa.Column('perm_id', sa.Integer(), nullable=False, comment='Код разрешения'),
        sa.ForeignKeyConstraint(
            ['perm_id'], ['permissions.id'], name=op.f('users_perms_fk_perm_id'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_perms_fk_user_id'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'perm_id', name=op.f('users_perms_pk'))
    )
    op.create_table(
        'users_roles',
        sa.Column('user_id', sa.Integer(), nullable=False, comment='Код пользователя'),
        sa.Column('role_id', sa.Integer(), nullable=False, comment='Код роли'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('users_roles_fk_role_id'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_roles_fk_user_id'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('users_roles_pk'))
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('users_perms')
    # ### end Alembic commands ###
