"""Init

Revision ID: bda6dd7ff42d
Revises:
Create Date: 2025-01-17 12:43:39.271115

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bda6dd7ff42d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'permissions',
        sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный ключ'),
        sa.Column('perm_code', sa.String(length=100), nullable=False, comment='Код разрешения'),
        sa.Column('perm_name', sa.String(length=150), nullable=False, comment='Имя разрешения'),
        sa.Column('perm_desc', sa.String(length=200), nullable=True, comment='Описание разрешения'),
        sa.Column('owner_cr', sa.Integer(), nullable=True, comment='Код создателя'),
        sa.Column('owner_up', sa.Integer(), nullable=True, comment='Код редактора'),
        sa.Column('dt_cr', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Создана'),
        sa.Column('dt_up', sa.DateTime(), nullable=True, comment='Изменена'),
        sa.Column('status', sa.Boolean(), server_default='true', nullable=False, comment='Статус'),
        sa.PrimaryKeyConstraint('id', name=op.f('permissions_pk'))
        )
    op.create_index(op.f('permissions_ix_status'), 'permissions', ['status'], unique=False)
    op.create_index('permissions_uq_perm_code', 'permissions', [sa.text('lower(perm_code)')], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('permissions_uq_perm_code', table_name='permissions')
    op.drop_index(op.f('permissions_ix_status'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
