"""User

Revision ID: 068473216256
Revises:
Create Date: 2025-01-21 13:51:41.085462

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '068473216256'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный ключ'),
        sa.Column('user_name', sa.String(length=100), nullable=False, comment='Имя пользователя'),
        sa.Column('user_mail', sa.String(length=100), nullable=True, comment='Адрес пользователя'),
        sa.Column('user_pass', sa.String(length=100), nullable=False, comment='Пароль пользователя'),
        sa.Column('user_desc', sa.String(length=150), nullable=True, comment='Описание пользователя'),
        sa.Column('user_avatar', sa.String(length=100), nullable=True, comment='Аватар пользователя'),
        sa.Column('sd_id', sa.Integer(), nullable=True, comment='Код подразделения пользователя'),
        sa.Column('last_login', sa.DateTime(), nullable=True, comment='Последний вход'),
        sa.Column('verification_code', sa.String(length=100), nullable=True, comment='Проверочный код'),
        sa.Column('owner_cr', sa.Integer(), nullable=True, comment='Код создателя'),
        sa.Column('owner_up', sa.Integer(), nullable=True, comment='Код редактора'),
        sa.Column('dt_ac', sa.DateTime(), nullable=True, comment='Активирована'),
        sa.Column('dt_cr', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Создана'),
        sa.Column('dt_up', sa.DateTime(), nullable=True, comment='Изменена'),
        sa.Column('status', sa.Boolean(), server_default='true', nullable=False, comment='Статус'),
        sa.PrimaryKeyConstraint('id', name=op.f('users_pk')),
        sa.UniqueConstraint('verification_code', name=op.f('users_uq_verification_code'))
    )
    op.create_index(op.f('users_ix_sd_id'), 'users', ['sd_id'], unique=False)
    op.create_index(op.f('users_ix_status'), 'users', ['status'], unique=False)
    op.create_index('users_uq_user_mail', 'users', [sa.text('lower(user_mail)')], unique=True)
    op.create_index('users_uq_user_name', 'users', [sa.text('lower(user_name)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_uq_user_name', table_name='users')
    op.drop_index('users_uq_user_mail', table_name='users')
    op.drop_index(op.f('users_ix_status'), table_name='users')
    op.drop_index(op.f('users_ix_sd_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
